This notebook is intended to normalize datasets

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
os.chdir('/Users/JohanLg/Documents/My Documents/SoÌˆka Jobb/OneField')

In [103]:
data = pd.read_excel('Data Set for Johan.xlsx', sheet_name = 'GDP YoY% (raw)')
urb = pd.read_excel('Data Set for Johan.xlsx', sheet_name = 'Urbanisation (raw)')
cap =  pd.read_excel('Data Set for Johan.xlsx', sheet_name = 'GDP per capita PPP USD (raw)')
pop =  pd.read_excel('Data Set for Johan.xlsx', sheet_name = 'Population (normalised)')

In [126]:
cap.head(10)

,YEAR,1980-12-31 00:00:00,1981-12-31 00:00:00,1982-12-31 00:00:00,1983-12-31 00:00:00,1984-12-31 00:00:00,1985-12-31 00:00:00,1986-12-31 00:00:00,1987-12-31 00:00:00,1988-12-31 00:00:00,...,2041-12-31 00:00:00,2042-12-31 00:00:00,2043-12-31 00:00:00,2044-12-31 00:00:00,2045-12-31 00:00:00,2046-12-31 00:00:00,2047-12-31 00:00:00,2048-12-31 00:00:00,2049-12-31 00:00:00,2050-12-31 00:00:00
0,Source,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,...,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB,IMF & WB
1,Period,FY,FY,FY,FY,FY,FY,FY,FY,FY,...,FY,FY,FY,FY,FY,FY,FY,FY,FY,FY
2,DataUnit,USD,USD,USD,USD,USD,USD,USD,USD,USD,...,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
3,MetricNature,Actual,Actual,Actual,Actual,Actual,Actual,Actual,Actual,Actual,...,Forecast,Forecast,Forecast,Forecast,Forecast,Forecast,Forecast,Forecast,Forecast,Forecast
4,Indicator,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,...,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP,GDP per Capita PPP
5,Product,Macro,Macro,Macro,Macro,Macro,Macro,Macro,Macro,Macro,...,Macro,Macro,Macro,Macro,Macro,Macro,Macro,Macro,Macro,Macro
6,DataFamily,Value,Value,Value,Value,Value,Value,Value,Value,Value,...,Value,Value,Value,Value,Value,Value,Value,Value,Value,Value
7,Canada,11786.1,13184,13391.1,14135,15364.4,16449.2,16972.9,17874.4,19065.5,...,58302.2,58302.2,58302.2,58302.2,58302.2,58302.2,58302.2,58302.2,58302.2,58302.2
8,USA,12552.9,13948.7,14405,15513.7,17086.4,18199.3,19034.8,20001,21376,...,76252.1,76252.1,76252.1,76252.1,76252.1,76252.1,76252.1,76252.1,76252.1,76252.1
9,United Kingdom,8852.52,9610.55,10421.9,11282.3,11935.8,12797,13433.7,14465.1,15806.3,...,54378.1,54378.1,54378.1,54378.1,54378.1,54378.1,54378.1,54378.1,54378.1,54378.1

In [127]:
data_ind = data.loc[0:6]
data_raw = data.loc[7:]

urb_ind = urb.loc[0:6]
urb_raw = urb.loc[7:]

cap_ind = cap.loc[0:6]
cap_raw = cap.loc[7:]

In [128]:
dat1 = pd.DataFrame()
dat2 = pd.DataFrame()
def melter(data1, data2): 
    global Final
    dat1 = pd.melt(frame = data1, id_vars = ['YEAR'])
    dat2 = pd.melt(frame = data2, id_vars = ['YEAR'])
    datfin = dat2.pivot(index = 'variable', columns = 'YEAR', values = 'value')
    Final = datfin.join(dat1.set_index('variable'), on = 'variable')
    Final['Year'] = Final.index
    return Final

In [129]:
melter(data_raw,data_ind)
Final_GDP = Final

In [130]:
melter(urb_raw, urb_ind)
Final_URB = Final

In [131]:
melter(cap_raw, cap_ind)
Final_CAP = Final

In [132]:
Final_GDP.columns = [['DataFamily','DataUnit','Indicator','MetricNature','Period','Product','Source','Country','GDP', 'Year' ]]
Final_URB.columns = [['DataFamily','DataUnit','Indicator','MetricNature','Period','Product','Source','Country','Urbanisation', 'Year' ]]
Final_CAP.columns = [['DataFamily','DataUnit','Indicator','MetricNature','Period','Product','Source','Country','GDP/Capita', 'Year' ]]

In [133]:
Final_GDP.head()

,DataFamily,DataUnit,Indicator,MetricNature,Period,Product,Source,Country,GDP,Year
variable,,,,,,,,,,
1980-12-31,Change,Percentage,GDP,Actual,FY,Macro,IMF,Canada,0.02163,1980-12-31
1980-12-31,Change,Percentage,GDP,Actual,FY,Macro,IMF,USA,-0.00257,1980-12-31
1980-12-31,Change,Percentage,GDP,Actual,FY,Macro,IMF,United Kingdom,-0.02028,1980-12-31
1980-12-31,Change,Percentage,GDP,Actual,FY,Macro,IMF,Ireland,0.02898,1980-12-31
1980-12-31,Change,Percentage,GDP,Actual,FY,Macro,IMF,Iceland,0.05738,1980-12-31

In [134]:
Final_URB.head()

,DataFamily,DataUnit,Indicator,MetricNature,Period,Product,Source,Country,Urbanisation,Year
variable,,,,,,,,,,
1980-12-31,Achievement,Percentage,Urbanisation,Actual,FY,Macro,UN,Canada,0.75663,1980-12-31
1980-12-31,Achievement,Percentage,Urbanisation,Actual,FY,Macro,UN,USA,0.73738,1980-12-31
1980-12-31,Achievement,Percentage,Urbanisation,Actual,FY,Macro,UN,United Kingdom,0.78481,1980-12-31
1980-12-31,Achievement,Percentage,Urbanisation,Actual,FY,Macro,UN,Ireland,0.55333,1980-12-31
1980-12-31,Achievement,Percentage,Urbanisation,Actual,FY,Macro,UN,Iceland,0.8826,1980-12-31

In [135]:
Final_CAP.head()

,DataFamily,DataUnit,Indicator,MetricNature,Period,Product,Source,Country,GDP/Capita,Year
variable,,,,,,,,,,
1980-12-31,Value,USD,GDP per Capita PPP,Actual,FY,Macro,IMF & WB,Canada,11786.1,1980-12-31
1980-12-31,Value,USD,GDP per Capita PPP,Actual,FY,Macro,IMF & WB,USA,12552.9,1980-12-31
1980-12-31,Value,USD,GDP per Capita PPP,Actual,FY,Macro,IMF & WB,United Kingdom,8852.52,1980-12-31
1980-12-31,Value,USD,GDP per Capita PPP,Actual,FY,Macro,IMF & WB,Ireland,7197.9,1980-12-31
1980-12-31,Value,USD,GDP per Capita PPP,Actual,FY,Macro,IMF & WB,Iceland,11064.3,1980-12-31

In [136]:
Final_GDP.to_csv('GDP.csv')
Final_URB.to_csv('URB.csv')
Final_CAP.to_csv('CAP.csv')

In [8]:
pop.to_csv('POP.csv')